language: java

jdk:
  - oraclejdk8
dist: trusty

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: ebuy-gateway-service
  on: master

before_install:
  - chmod +x mvnw

install: true

script: mvn clean package -DskipTests=true